SET SERVEROUTPUT ON;
-- CREATE AND GRANT PERMISSIONS TO WAREHOUSE_APP_ADMIN ROLE
-- Drop the role if already exists
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE WAREHOUSE_APP_ADMIN';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1919 THEN
          dbms_output.put_line('ROLE WAREHOUSE_APP_ADMIN doesnot exist ');
        END IF;
END;
/
CREATE ROLE WAREHOUSE_APP_ADMIN;
GRANT CONNECT TO WAREHOUSE_APP_ADMIN;
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO WAREHOUSE_APP_ADMIN;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO WAREHOUSE_APP_ADMIN;

-- CREATE WAREHOUSE_APP_ADMIN_USER  ASSIGN WAREHOUSE_APP_ADMIN ROLE
-- Drop the user if already exists
BEGIN
    EXECUTE IMMEDIATE 'DROP USER WAREHOUSE_APP_ADMIN_USER CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1918 THEN
           dbms_output.put_line('User WAREHOUSE_APP_ADMIN_USER doesnot exist ');
        END IF;
END;
/

CREATE USER WAREHOUSE_APP_ADMIN_USER IDENTIFIED BY BostonSpring2024#;
GRANT WAREHOUSE_APP_ADMIN TO WAREHOUSE_APP_ADMIN_USER;
ALTER USER WAREHOUSE_APP_ADMIN_USER DEFAULT ROLE WAREHOUSE_APP_ADMIN;
ALTER USER WAREHOUSE_APP_ADMIN_USER DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER WAREHOUSE_APP_ADMIN_USER TEMPORARY TABLESPACE TEMP;













