CREATE ROLE WAREHOUSE_APP_ADMIN;

CREATE ROLE WAREHOUSE_OWNER;

CREATE ROLE WAREHOUSE_USER;

CREATE ROLE WAREHOUSE_EMPLOYEE;

-- GRANT PERMISSIONS TO WAREHOUSE_APP_ADMIN
GRANT CREATE SESSION TO WAREHOUSE_APP_ADMIN;
GRANT CONNECT TO WAREHOUSE_APP_ADMIN;
