DROP SEQUENCE Customer_ID_SEQ;
DROP SEQUENCE Location_ID_SEQ;
DROP SEQUENCE Warehouse_Type_ID_SEQ;
DROP SEQUENCE Owner_ID_SEQ;
DROP SEQUENCE Warehouse_ID_SEQ;
DROP SEQUENCE Employee_ID_SEQ;
DROP SEQUENCE Service_Request_ID_SEQ;
DROP SEQUENCE Payment_ID_SEQ;
DROP SEQUENCE Lease_Unit_ID_SEQ;
DROP SEQUENCE Lease_ID_SEQ;
DROP SEQUENCE Unit_ID_SEQ;



CREATE SEQUENCE Customer_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE Location_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE Warehouse_Type_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE Owner_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE Warehouse_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
CREATE SEQUENCE Employee_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE Service_Request_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE Payment_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE Lease_Unit_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE Lease_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE Unit_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
